### ISSUE TITLE
Review needed

### ISSUE THREAD

**Issue by bastienjacoud** [PolytechLyon/isi3-singleton-remond-jacoud-tp5#1]
TP sur le singleton terminé.

Cordialement, 
Bastien

**Comment by Slashgear** [comment]
- C'est pas mal déjà
- [ ] Pour l'autowiring, c'est pas une spécificité de Spring par annotation. On peut le faire dans le xml. Pour la peine donnez moi la conf xml qui permettrait de charger le bean logger automagiquement en xml sans passer par une ref.
- [ ] Pour la partie SpringBoot c'est pas mal. Mais pour les properties on y définie souvent les constantes de l'application au format string. Quand on peut changer des configuration de Bean avec spring on peut passer par des Spring Profil.
Voici un exemple (en conf xml et par annotation)
https://jeanchristophegay.com/spring-et-les-profils/
En changeant le profil on pourra alors changer un Bean ou non

**Comment by bastienjacoud** [comment]
J'ai modifié mon code et push les modifications pour répondes à vos deux exigeances ci-dessus, @Slashgear .

Pour la première, j'ai modifié le fichier de configuration xml en ajoutant aux beans "personn" et "cat" l'attribut autowire="byName". Il est également possible de choisir autowire="byType". 

Pour la seconde, j'ai modifé mon code afin d'avoir 2 fonctions de créations de Beans (ConsoleLogger et FileLogger). J'ai attribué à chaque méthode un profil avec l'annotation @Profile("a") ou @Profile("b") juste au dessus de la fonction. Dans mon fichier application.properties, j'ai ajouté : spring.profiles.active=a ou b qui va indiquer à notre application quel profil chosir entre les deux définis et ainsi quel bean choisir pour créer notre logger. 

Cordialement, 
Bastien

**Comment by Slashgear** [comment]
👌
